Repository patha454/prim, pull requests merged in 2020-05, with the labels that each got.

#1 Feature: Initial CMake specification.
  .gitignore
  CMakeLists.txt
  main.c
Labels: enhancement

#2 CI: Build on push.
  .github/workflows/build.yml
Labels: enhancement

#3 CI: Lint with clang-tidy
  .github/workflows/lint.yml
Labels: CI

#4 Documentation: Initial readme.
  README.md
Labels: documentation

#5 Documentation: Add CI badges.
  README.md
Labels: documentation

#6 Feature: ELF64 types.
  CMakeLists.txt
  include/format/elf64/types.h
  main.c
Labels: enhancement

#8 CI: Clang-tidy profile.
  .clang-tidy
  .github/workflows/lint.yml
  .gitignore
  main.c
Labels: CI

#9 Bugfix: Unsign Elf64_Word, Elf64_Xword.
  include/format/elf64/types.h
Labels: bug

#10 Feature: ELF64 header definition.
  include/format/elf64/header.h
Labels: enhancement

#11 Style: Improve header guard.
  include/format/elf64/header.h
Labels: enhancement

#12 Feature: Platform type abstraction.
  include/format/elf64/types.h
  include/platform/types.h
Labels: enhancement

#14 Style: Improve formating.
  include/platform/types.h
Labels: enhancement

#15 Bugfix: Linter warnings as errors.
  .clang-tidy
  include/status.h
Labels: bug

#16 Style: Move main to src.
  CMakeLists.txt
  src/main.c
Labels: style

#17 Documentation: Add build instructions.
  README.md
Labels: documentation

#18 Documentation: Add project objectives.
  README.md
Labels: documentation

#19 Feature: File handling abstraction.
  .clang-tidy
  CMakeLists.txt
  include/platform/file.h
  include/status.h
  src/main.c
  src/platform/file.c
  src/status.c
Labels: enhancement

#20 Refactor: remove old main.c from linting.
  .github/workflows/lint.yml
Labels: style

#21 Feature: ELF64 ident handling.
  CMakeLists.txt
  include/format/elf64/header.h
  include/format/elf64/ident.h
  src/format/elf64/ident.c
  src/main.c
Labels: enhancement

#23 Feature: ELF64 types and machine handling.
  CMakeLists.txt
  include/format/elf64/header.h
  src/format/elf64/header.c
  src/main.c
Labels: enhancement

#22 Style: Fix typos.
  src/format/elf64/ident.c
Labels: style

#24 Style: Restyle with clang-format
  .clang-format
  .github/workflows/style.yml
  include/format/elf64/header.h
  include/format/elf64/ident.h
  include/format/elf64/types.h
  include/platform/file.h
  include/platform/types.h
  src/format/elf64/header.c
  src/format/elf64/ident.c
  src/main.c
  src/platform/file.c
  src/status.c
Labels: style

#25 CI: Add style check badge.
  README.md
Labels: CI

#26 Style: Add bin packing rules.
  .clang-format
  include/format/elf64/header.h
  include/format/elf64/ident.h
  include/platform/file.h
  include/platform/types.h
  include/status.h
  src/format/elf64/header.c
  src/format/elf64/ident.c
  src/main.c
  src/platform/file.c
  src/status.c
Labels: style

#27 Feature: Full ELF64 header implimentation.
  include/format/elf64/header.h
  src/format/elf64/header.c
  src/main.c
Labels: enhancement

#28 Documentation: Add linting instructions.
  README.md
Labels: documentation

#29 CI: Enforce C99 standard.
  .github/workflows/build.yml
  README.md
Labels: CI

#30 Feature: Take file from command line args.
  src/main.c
Labels: enhancement

#31 Documentation: Shorten linting command.
  README.md
Labels: documentation

#32 CI: Shorten lint command
  .github/workflows/lint.yml
Labels: CI

#33 Feature: ELF64 section headers.
  CMakeLists.txt
  include/format/elf64/section.h
  src/format/elf64/header.c
  src/format/elf64/section.c
  src/main.c
Labels: enhancement

#34 Feature: Add section name access.
  include/format/elf64/section.h
  src/format/elf64/section.c
  src/main.c
Labels: enhancement

#35 Refactor: Split ELF64 headers into subfiles.
  CMakeLists.txt
  include/format/elf64/header/header.h
  include/format/elf64/header/ident.h
  include/format/elf64/header/machine.h
  include/format/elf64/header/type.h
  include/format/elf64/section.h
  include/format/elf64/section/flags.h
  include/format/elf64/section/header.h
  include/format/elf64/section/type.h
  src/format/elf64/header.c
  src/format/elf64/header/header.c
  src/format/elf64/header/ident.c
  src/format/elf64/header/machine.c
  src/format/elf64/header/type.c
  src/format/elf64/section.c
  src/format/elf64/section/flags.c
  src/format/elf64/section/header.c
  src/format/elf64/section/type.c
  src/main.c
Labels: refactor

#36 Refactor: Remove ELF64 sub-file dependence on header.
  include/format/elf64/header/header.h
  include/format/elf64/header/ident.h
  include/format/elf64/header/machine.h
  include/format/elf64/header/type.h
  src/format/elf64/header/ident.c
  src/format/elf64/header/machine.c
  src/format/elf64/header/type.c
  src/main.c
Labels: refactor

#39 Bugfix: Fix section flag validation.
  src/format/elf64/section/flags.c
Labels: bug

#37 Bugfix: Alloc SHT_USER and SHT_PROC section type ranges.
  src/format/elf64/section/type.c
  src/main.c
Labels: bug

#38 Bugfux: Allow ELF64 proc defined type range.
  src/format/elf64/header/type.c
Labels: bug

#40 Feature: Add LSB5 section types to ELF64.
  include/format/elf64/section/type.h
  src/format/elf64/section/type.c
Labels: enhancement

#46 Feature: Add platform memory interface.
  CMakeLists.txt
  include/platform/memory.h
  include/platform/types.h
  src/platform/memory.c
Labels: enhancement

#47 Feature: ELF64 section string tables
  CMakeLists.txt
  include/format/elf64/section/string_table.h
  src/format/elf64/section/string_table.c
  src/main.c
Labels: enhancement

#48 Refactor: Split libprim and prim_app.
  CMakeLists.txt
  libprim/include/format/elf64/header/header.h
  libprim/include/format/elf64/header/ident.h
  libprim/include/format/elf64/header/machine.h
  libprim/include/format/elf64/header/type.h
  libprim/include/format/elf64/section/flags.h
  libprim/include/format/elf64/section/header.h
  libprim/include/format/elf64/section/string_table.h
  libprim/include/format/elf64/section/type.h
  libprim/include/format/elf64/types.h
  libprim/include/platform/file.h
  libprim/include/platform/memory.h
  libprim/include/platform/types.h
  libprim/include/status.h
  libprim/src/format/elf64/header/header.c
  libprim/src/format/elf64/header/ident.c
  libprim/src/format/elf64/header/machine.c
  libprim/src/format/elf64/header/type.c
  libprim/src/format/elf64/section/flags.c
  libprim/src/format/elf64/section/header.c
  libprim/src/format/elf64/section/string_table.c
  libprim/src/format/elf64/section/type.c
  libprim/src/platform/file.c
  libprim/src/platform/memory.c
  libprim/src/status.c
  prim_app/src/main.c
Labels: refactor

#49 Refactor: Modular CMakeLists.
  CMakeLists.txt
  libprim/CMakeLists.txt
  libprim/src/CMakeLists.txt
  libprim/src/format/CMakeLists.txt
  libprim/src/format/elf64/CMakeLists.txt
  libprim/src/format/elf64/header/CMakeLists.txt
  libprim/src/format/elf64/section/CMakeLists.txt
  libprim/src/platform/CMakeLists.txt
  prim_app/CMakeLists.txt
  prim_app/src/CMakeLists.txt
Labels: refactor
